name: Publish Website

on: push

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Fast FTP Action
      uses: anvil-solutions/Fast-FTP-Action@2.1.0
      with:
        server: ftp.samkirklan7d.com
        port: 2222
        username: myFtpUserName
        password: 11219
